# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is read only once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
# baseurl: lennertderyckbe # the subpath of your site, e.g. /blog
host   : 127.0.0.1
port   : 4000

# Custom Site variables
# ─────────────────────
show-style-guide: false # Show style guide in footer.
title: Lennert De Ryck

# Build settings
# ──────────────
highlighter: rouge
livereload: true

exclude:
  - Gemfile
  - README.md
  - vendor/bundle

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-menus

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed

collections:
  repos:
    output: true
  projects:
    output: true
  redirects:
    output: true

defaults:
  - scope:
      path: ""
      type: "repos"
    values:
      layout: "repo"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      widgets-bottom: false
  - scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"
