---
label: Project
hide_body: false
fields:
- name: date
  type: datetime
  label: Datum publicatie
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: tags
  type: select
  default: Web
  config:
    required: false
    options:
    - Web
    - Print
    - Sign
    - Branding
    - Online
    - Fotografie
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Type
- type: text
  name: title
  label: Titel
- type: text
  name: client
  label: Klant
- type: text
  name: project-url
  label: Project link
  config:
    min: '10'
- name: ft-img
  type: file
  config:
    maxSize: 250
  label: Feature image
- type: image_gallery
  name: galery
  label: Galerij
pages:
- _projects/parkeergarages-gent.md
- _projects/the-meal-database.md
- _projects/triva-quiz.md
- _projects/tronald-dump.md
